version: 0.1
phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket toshihirock-samlocal --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - outputSamTemplate.yaml
