version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket case1089736813 --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - outputSamTemplate.yaml
